name: m1
dependencies:
  - apple::tensorflow-deps==2.6.0
  - bz2file
  - cython
  - jupyter
  - matplotlib==3.5.0
  - numpy==1.19.5
  - pandas==1.3.4
  - pillow==8.4.0
  - pip==21.3.1
  - pylint
  - pytest
  - python
  - scikit-learn==1.0.1
  - scipy==1.7.3
  - seaborn==0.11.2
  - setuptools
  - twisted
  - pip:
      - playsound
      - simpleaudio
      - tensorflow-macos
      - tensorflow-metal
