name: m1
dependencies:
  - apple::tensorflow-deps
  - bz2file
  - cython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pylint
  - pytest
  - python
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - twisted
  - pip:
      - playsound
      - scikeras
      - simpleaudio
      - tensorflow-macos
      - tensorflow-metal
